-- Generated from generator/demo_specs/aws-thailand-tourism-demand-forecast.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-thailand-tourism-demand-forecast
-- This is the schema that is actually deployed for THAILAND_TOURISM_DEMAND_FORECAST.

-- Alerts fire on the bottom tail of Arrivals Forecast (30d)
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_ARRIVALS_FORECAST_30D) AS T
  FROM RAW.SEARCH_TRENDS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_ARRIVALS_FORECAST_30D <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_ARRIVALS_FORECAST_30D), 2) AS AVG_ARRIVALS_FORECAST_30D,
  ROUND(AVG(f.KPI_REVENUE_FORECAST), 2) AS AVG_REVENUE_FORECAST,
  ROUND(AVG(f.KPI_FORECAST_ACCURACY), 2) AS AVG_FORECAST_ACCURACY,
  ROUND(AVG(f.KPI_CHINA_RECOVERY), 2) AS AVG_CHINA_RECOVERY,
  ROUND(AVG(f.KPI_AVG_SPEND_TOURIST), 2) AS AVG_SPEND_TOURIST,
  ROUND(AVG(f.KPI_VISA_FREE_IMPACT), 2) AS AVG_VISA_FREE_IMPACT
FROM RAW.SEARCH_TRENDS f
JOIN RAW.THAI_TOURISM_POLICY e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_ARRIVALS_FORECAST_30D), 2) AS AVG_ARRIVALS_FORECAST_30D,
  ROUND(AVG(f.KPI_REVENUE_FORECAST), 2) AS AVG_REVENUE_FORECAST,
  ROUND(AVG(f.KPI_FORECAST_ACCURACY), 2) AS AVG_FORECAST_ACCURACY,
  ROUND(AVG(f.KPI_CHINA_RECOVERY), 2) AS AVG_CHINA_RECOVERY,
  ROUND(AVG(f.KPI_AVG_SPEND_TOURIST), 2) AS AVG_SPEND_TOURIST,
  ROUND(AVG(f.KPI_VISA_FREE_IMPACT), 2) AS AVG_VISA_FREE_IMPACT
FROM RAW.SEARCH_TRENDS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_ARRIVALS_FORECAST_30D) AS KPI_ARRIVALS_FORECAST_30D, AVG(KPI_REVENUE_FORECAST) AS KPI_REVENUE_FORECAST, AVG(KPI_FORECAST_ACCURACY) AS KPI_FORECAST_ACCURACY, AVG(KPI_CHINA_RECOVERY) AS KPI_CHINA_RECOVERY, AVG(KPI_AVG_SPEND_TOURIST) AS KPI_AVG_SPEND_TOURIST, AVG(KPI_VISA_FREE_IMPACT) AS KPI_VISA_FREE_IMPACT FROM RAW.SEARCH_TRENDS),
     en AS (SELECT SUM(KPI_MARKETS_TRACKED) AS KPI_MARKETS_TRACKED FROM RAW.THAI_TOURISM_POLICY)
  SELECT 1 AS SORT_ORDER, 'Arrivals Forecast (30d)' AS TITLE, KPI_ARRIVALS_FORECAST_30D AS VALUE_NUM, TO_VARCHAR(CAST(ROUND(((KPI_ARRIVALS_FORECAST_30D) / 1000000), 1) AS DECIMAL(38,1))) || 'M' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'Revenue Forecast' AS TITLE, KPI_REVENUE_FORECAST AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_REVENUE_FORECAST) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Forecast Accuracy' AS TITLE, KPI_FORECAST_ACCURACY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_FORECAST_ACCURACY), 1) AS DECIMAL(38,1))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Markets Tracked' AS TITLE, KPI_MARKETS_TRACKED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_MARKETS_TRACKED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'China Recovery' AS TITLE, KPI_CHINA_RECOVERY AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_CHINA_RECOVERY)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Avg Spend/Tourist' AS TITLE, KPI_AVG_SPEND_TOURIST AS VALUE_NUM, '฿' || TO_VARCHAR(CAST(ROUND(((KPI_AVG_SPEND_TOURIST) / 1000)) AS DECIMAL(38,0))) || 'K' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'Visa-Free Impact' AS TITLE, KPI_VISA_FREE_IMPACT AS VALUE_NUM, '+' || TO_VARCHAR(CAST(ROUND((KPI_VISA_FREE_IMPACT)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
