-- ============================================================================
-- 06_ML_MODELS.SQL — ML Functions for Tourism Demand Forecasting
-- ============================================================================
USE DATABASE TOURISM_DEMAND;
USE SCHEMA ML;

-- ML.FORECAST: ARRIVAL_FORECAST_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.FORECAST ML.ARRIVAL_FORECAST_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.ARRIVAL_TIMESERIES'),
  SERIES_COLNAME => 'MARKET_DESTINATION',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y'
  
);

CREATE OR REPLACE TABLE ML.ARRIVAL_FORECAST_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.ARRIVAL_FORECAST_MODEL!FORECAST(FORECASTING_PERIODS => 14));

-- ML.ANOMALY_DETECTION: DEMAND_ANOMALY_MODEL
CREATE OR REPLACE SNOWFLAKE.ML.ANOMALY_DETECTION ML.DEMAND_ANOMALY_MODEL(
  INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.ARRIVAL_TIMESERIES'),
  SERIES_COLNAME => 'MARKET_DESTINATION',
  TIMESTAMP_COLNAME => 'DS',
  TARGET_COLNAME => 'Y',
  LABEL_COLNAME => ''
);

CREATE OR REPLACE TABLE ML.DEMAND_ANOMALY_MODEL_RESULTS AS
SELECT * FROM TABLE(ML.DEMAND_ANOMALY_MODEL!DETECT_ANOMALIES(INPUT_DATA => SYSTEM$REFERENCE('TABLE', 'CURATED.ARRIVAL_TIMESERIES'), SERIES_COLNAME => 'MARKET_DESTINATION', TIMESTAMP_COLNAME => 'DS', TARGET_COLNAME => 'Y'));

