-- ============================================================================
-- 99_RESET.SQL — Reset Tourism Demand Forecasting to clean demo state
-- ============================================================================
USE DATABASE TOURISM_DEMAND;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_UPDATE_INDICATORS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_GENERATE_BRIEFS SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.ARRIVAL_TIMESERIES REFRESH;
ALTER DYNAMIC TABLE CURATED.DEMAND_LEADING_INDICATORS REFRESH;
ALTER DYNAMIC TABLE CURATED.FORECAST_VS_ACTUAL REFRESH;
ALTER DYNAMIC TABLE CURATED.CAPACITY_UTILIZATION REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM TOURISM_DEMAND.RAW.ARRIVAL_HISTORY → 146000
-- SELECT COUNT(*) FROM TOURISM_DEMAND.RAW.SEARCH_TRENDS → 300000
-- SELECT COUNT(DISTINCT MARKET_DESTINATION) FROM TOURISM_DEMAND.CURATED.ARRIVAL_TIMESERIES → 100

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_GENERATE_BRIEFS RESUME;
ALTER TASK IF EXISTS APP.TASK_UPDATE_INDICATORS RESUME;
ALTER TASK IF EXISTS APP.TASK_REFRESH_FORECASTS RESUME;
